import { useEffect, useRef } from 'react';
import { applyTwoCol, fontScaleValue } from '../lib/chords';

interface ChordSheetProps {
  html: string;
  twoCol?: boolean;
  fontSize?: number;
}

export function ChordSheet({ html, twoCol, fontSize }: ChordSheetProps) {
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (twoCol) applyTwoCol();
  }, [html, twoCol]);

  const scale = fontScaleValue(fontSize || 0);

  return (
    <div
      className="chord-sheet-wrap"
      ref={wrapRef}
      style={scale ? { '--font-scale': scale } as React.CSSProperties : undefined}
    >
      {/* html is generated by ChordSheetJS formatter from user chord content */}
      <div id="chord-output" dangerouslySetInnerHTML={{ __html: html }} />
    </div>
  );
}
