import { forwardRef } from 'react';
import { fontScaleValue } from '../lib/chords';

interface ChordSheetProps {
  html: string;
  twoCol?: boolean;
  fontSize?: number;
}

export const ChordSheet = forwardRef<HTMLDivElement, ChordSheetProps>(
  ({ html, twoCol, fontSize }, ref) => {
    const scale = fontScaleValue(fontSize || 0);
    const cls = `chord-sheet-wrap${twoCol ? ' two-col' : ''}`;

    return (
      <div
        ref={ref}
        className={cls}
        style={scale ? { '--font-scale': scale } as React.CSSProperties : undefined}
      >
        {/* html is generated by ChordSheetJS formatter from user chord content */}
        <div id="chord-output" dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    );
  }
);

ChordSheet.displayName = 'ChordSheet';
