const ROLES = { OWNER: 'owner', ADMIN: 'admin', USER: 'user' };

const STATUS = { ACTIVE: 'active', PENDING: 'pending' };

const VISIBILITY = { PUBLIC: 'public', PRIVATE: 'private' };

const LIMITS = {
  MAX_TITLE: 200,
  MAX_CONTENT: 100_000,
  MAX_BPM: 300,
  MIN_BPM: 1,
  MAX_SETLIST_NAME: 200,
  MAX_IMPORT: 500,
  MAX_REORDER: 1000,
  MAX_YOUTUBE_URL: 500,
  TRANSPOSE_MIN: -12,
  TRANSPOSE_MAX: 12,
  USERNAME_MIN: 3,
  USERNAME_MAX: 50,
  PASSWORD_MIN: 6,
  GEMINI_KEY_MIN: 20,
  GEMINI_KEY_MAX: 100,
  MAX_OCR_IMAGE: 10 * 1024 * 1024,
  MAX_PREFERRED_LANGUAGES: 10,
  MAX_OCR_PROMPT: 5000,
};

module.exports = { ROLES, STATUS, VISIBILITY, LIMITS };
